services:
  postgres:
    image: postgres:15
    container_name: marketpulse_db
    restart: always
    environment:
      POSTGRES_USER: marketpulse
      POSTGRES_PASSWORD: marketpulsepassword
      POSTGRES_DB: marketpulse_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "marketpulse"]
      interval: 5s
      retries: 5
      timeout: 3s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: marketpulse_backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: marketpulse_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - NEXT_DISABLE_SWC=1
      - NEXT_PUBLIC_API_URL=http://marketpulse_backend:8000 # API calls must use this
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: ["pnpm", "dev"]

volumes:
  postgres_data:
